algoritmo "ConvertePesoKgGrama"
// Função : Recebe o valor do peso da pessoa em Kg converte e mostra esse peso em Gramas
// Autor : San Diego - Lista 01
// Data : 23/05/2017
var
peso: Real
inicio

escreva("Digite se peso (Kg): ")
leia(peso)

peso <- peso * 1000

escreval("-----------------------------------------")
escreval("Você pesa o equivalente a ",peso," Gramas")
escreval("-----------------------------------------")

fimalgoritmo
