algoritmo "MediaPonderada"
// Função : Calcular e mostrar a média poderada entre duas notas digitadas
// Autor : San Diego - Lista 01
// Data : 23/05/2017
var
nota1, nota2, media:Real
inicio

escreva("Digite o valor da primeira nota: ")
leia(nota1)
escreva("Digite o valor da segunda nota: ")
leia(nota2)

media <- ((nota1 * 2) + (nota2 * 3)) / 5

escreva("A média ponderada vale: ", media)
fimalgoritmo
